import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header.component";
import Footer from "./components/footer/footer.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:mx-[10%] lg:mx-[20%] sm:mx-[5%] mx-2 `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
